# Generated by Django 4.2 on 2025-07-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rpom_booking_delete_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rpom_Booking',
            new_name='Room_Booking',
        ),
    ]
