# Generated by Django 4.2 on 2025-07-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_rpom_booking_room_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_employee',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
