# Generated by Django 4.2 on 2025-07-07 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='date',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
