# Generated by Django 4.2 on 2025-07-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_room_amenities_room_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.TextField(default='AC, Projector', help_text='Comma-separated (e.g. AC, Projector)'),
        ),
    ]
